TwitterClone/Models/ErrorViewModel.cs
using System;

namespace TwitterClone.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TwitterClone/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TwitterClone.Models;

namespace TwitterClone.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TwitterClone/Controllers/TwitterController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TwitterClone.Model;
using TwitterClone.Model.Repositories;

namespace TwitterClone.Controllers
{
    public class TwitterController : Controller
    {
        //IPersonRepository _personRepository = null;
        //public TwitterController(IPersonRepository repository)
        //{
        //    _personRepository = repository;
        //}
        private PersonRepository personRepository = null;
        private TwitterRepository twitterRepository = null;
        private FollowingRepository followingRepository = null;
         public TwitterController()
        {
            twitterRepository = new TwitterRepository();
            personRepository = new PersonRepository();
            followingRepository = new FollowingRepository();
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Signup()
        {
            return View();
        }
        [HttpPost]
        public IActionResult SignUp(Person person)
        {
            personRepository.AddPerson(person);
            return RedirectToAction("Login");
        }
        [HttpGet]
        public IActionResult Login()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Login(Person person)
        {
            var status=personRepository.ValidatePerson(person.UserId, person.Password);
            if (status)
            {
                HttpContext.Session.SetString("userid", person.UserId);

                return RedirectToAction("UserDashboard");
            }
            else
            {
                ViewBag.ErrMsg = "Invalid Credentials";
                return View();
            }
        }
        [HttpGet]
        public IActionResult UserDashboard()
        {
            string id = HttpContext.Session.GetString("userid");
            Person person = personRepository.GetPerson(id);
            Tweet tweet = new Tweet();
            List<Tweet> tweets = twitterRepository.GetTweets(id);
            List<Person> persons = personRepository.GetPersons();
            ViewBag.Tweets = tweets.Count;
            ViewBag.Following = twitterRepository.GetFollowing(id).Count;
            ViewBag.Followers = twitterRepository.GetFollowers(id).Count;

            PersonTweetViewModel personTweetViewModel = new PersonTweetViewModel()
            {
                Person = person,
                Tweet = tweet,
                TweetsList = tweets.ToList(),
                Persons=persons

            };
          
            return View(personTweetViewModel);
         
        }
        [HttpPost]
        public IActionResult UserDashboard(PersonTweetViewModel personTweetViewModel)
        {
           
            Tweet tweet = new Tweet();
            ViewBag.Msg = "No tweets";
            string id = HttpContext.Session.GetString("userid");
            tweet.UserId= HttpContext.Session.GetString("userid");
            tweet.Created = DateTime.Now;
            tweet.Message = personTweetViewModel.Tweet.Message;
            twitterRepository.AddTweet(tweet);
            
            return RedirectToAction("UserDashboard");
        }
        [HttpGet]
        public IActionResult Details(string userid)
        {
            Person person = personRepository.GetPerson(userid);
           HttpContext.Session.SetString("followingid", userid); 
            Following following = new Following();
            PersonFollowViewModel personFollowViewModel = new PersonFollowViewModel()
            {
                Person = person,
                Following = following
            };
            return View(personFollowViewModel);
        }
        [HttpPost]
        public IActionResult Details(PersonFollowViewModel personFollowViewModel)
        {
            Random r = new Random();
            Following following = new Following();
            following.Id = r.Next(10, 10000000);
            following.UserId = HttpContext.Session.GetString("userid");
            following.FollowingId = HttpContext.Session.GetString("followingid");
            followingRepository.AddFollowing(following);
            return RedirectToAction("UserDashboard");
        }

        public IActionResult Profile()
        {
            string id = HttpContext.Session.GetString("userid");
            Person person = personRepository.GetPerson(id);
            return View(person);
        }

        public IActionResult LogOut()
        {
            HttpContext.Session.Clear(); //clears all the session data.
            return RedirectToAction("Login");
        }


    }
}

TwitterClone/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TwitterClone/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TwitterClone</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Twitter" asp-action="Login">TwitterClone</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li>

                        </li>
                        <li>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Twitter" asp-action="UserDashboard">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Twitter" asp-action="Profile">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Twitter" asp-action="Login">LogOut</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - TwitterClone - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TwitterClone/Views/Twitter/Details.cshtml
@model TwitterClone.Model.PersonFollowViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
    <style>
        td {
            padding: 15px;
            text-align: left;
        }
        td {
            border-bottom: 1px solid #ddd;
        }
        tr:hover {background-color: #f5f5f5;}
    </style>
</head>
<body>
    <center>
        <div>
            <h1>@Model.Person.Fullname</h1>
            <hr />
            <dl class="row">

                <table >
                    <tr>
                        <td> @Html.DisplayNameFor(model => model.Person.Fullname)</td>


                        <td> @Html.DisplayFor(model => model.Person.Fullname)</td>
                    </tr>
                    <tr>
                        <td>  @Html.DisplayNameFor(model => model.Person.Email)</td>

                        <td>   @Html.DisplayFor(model => model.Person.Email)</td>
                    </tr>
                    <tr>
                        <td>@Html.DisplayNameFor(model => model.Person.Joined)</td>

                        <td>@Html.DisplayFor(model => model.Person.Joined)</td>
                    </tr>
                </table>

            </dl>
        </div>
        <div>
            <form asp-action="Details">
                <div class="form-group">
                    <input type="submit" value="Follow" class="btn btn-primary" />
                </div>
            </form>
        </div>
        <div>
    </center>

    <a asp-action="Profile">Dashboard</a>
    </div>
</body>
</html>

TwitterClone/Views/Twitter/Login.cshtml
@model TwitterClone.Model.Person

@{
    ViewData["Title"] = "Login";
    Layout = null;
}
<style>
    .formstyle {
        max-width: 450px;
        font-family: "Lucida Sans Unicode", "Lucida Grande", sans-serif;
        text-align:center;
    }
    .formstyle label {
        display: block;
        margin-bottom: 10px;
    }
    .formstyle fieldset {
        border-radius: 10px;
        -webkit-border-radius: 10px;
        -moz-border-radius: 10px;
        margin: 0px 0px 10px 0px;
        border: 1px solid #FFD2D2;
        padding: 20px;
        background: #FFF4F4;
        box-shadow: inset 0px 0px 15px #FFE5E5;
        -moz-box-shadow: inset 0px 0px 15px #FFE5E5;
        -webkit-box-shadow: inset 0px 0px 15px #FFE5E5;
    }
    .formstyle fieldset legend {
        color: #FFA0C9;
        border-top: 1px solid #FFD2D2;
        border-left: 1px solid #FFD2D2;
        border-right: 1px solid #FFD2D2;
        border-radius: 5px 5px 0px 0px;
        -webkit-border-radius: 5px 5px 0px 0px;
        -moz-border-radius: 5px 5px 0px 0px;
        background: #FFF4F4;
        padding: 0px 8px 3px 8px;
        box-shadow: -0px -1px 2px #F1F1F1;
        -moz-box-shadow: -0px -1px 2px #F1F1F1;
        -webkit-box-shadow: -0px -1px 2px #F1F1F1;
        font-weight: normal;
        font-size: 12px;
    }
    .formstyle input[type=submit] {
        background: #EB3B88;
        border: 1px solid #C94A81;
        padding: 5px 15px 5px 15px;
        color: #FFCBE2;
        box-shadow: inset -1px -1px 3px #FF62A7;
        -moz-box-shadow: inset -1px -1px 3px #FF62A7;
        -webkit-box-shadow: inset -1px -1px 3px #FF62A7;
        border-radius: 3px;
        border-radius: 3px;
        -webkit-border-radius: 3px;
        -moz-border-radius: 3px;
        font-weight: bold;
    }
    h1 {
        color: #EB3B88;
    }
   
</style>

<hr />
<center>
<div class="total">
    <h1 class="h1">Welcome to Twitter Clone</h1>
    <div class="formstyle">
        <form asp-action="Login">
            <fieldset>
                <legend>Login</legend>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="UserId" class="control-label"></label>
                    <input asp-for="UserId" class="form-control" />
                    <span asp-validation-for="UserId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="control-label"></label>
                    <input asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group">
                    <input type="submit" value="Login" class="btn btn-primary" />
                </div>
            </fieldset>
        </form>

    </div>
</div>
<div>
    <h4>New User?</h4><a asp-action="SignUp">SignUp</a>

</div>
</center>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TwitterClone/Views/Twitter/Profile.cshtml
@model TwitterClone.Model.Person

@{
    ViewData["Title"] = "Profile";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Profile</h1>

<div>
    <h4>Person</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fullname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fullname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Joined)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Joined)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Active)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Active)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.UserId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TwitterClone/Views/Twitter/Signup.cshtml
@model TwitterClone.Model.Person

@{
    ViewData["Title"] = "Signup";
    Layout = null;
}

<style>
    .formstyle {
        max-width: 450px;
        font-family: "Lucida Sans Unicode", "Lucida Grande", sans-serif;
        text-align: center;
    }

        .formstyle label {
            display: block;
            margin-bottom: 10px;
        }

        .formstyle fieldset {
            border-radius: 10px;
            -webkit-border-radius: 10px;
            -moz-border-radius: 10px;
            margin: 0px 0px 10px 0px;
            border: 1px solid #FFD2D2;
            padding: 20px;
            background: #FFF4F4;
            box-shadow: inset 0px 0px 15px #FFE5E5;
            -moz-box-shadow: inset 0px 0px 15px #FFE5E5;
            -webkit-box-shadow: inset 0px 0px 15px #FFE5E5;
        }

            .formstyle fieldset legend {
                color: #FFA0C9;
                border-top: 1px solid #FFD2D2;
                border-left: 1px solid #FFD2D2;
                border-right: 1px solid #FFD2D2;
                border-radius: 5px 5px 0px 0px;
                -webkit-border-radius: 5px 5px 0px 0px;
                -moz-border-radius: 5px 5px 0px 0px;
                background: #FFF4F4;
                padding: 0px 8px 3px 8px;
                box-shadow: -0px -1px 2px #F1F1F1;
                -moz-box-shadow: -0px -1px 2px #F1F1F1;
                -webkit-box-shadow: -0px -1px 2px #F1F1F1;
                font-weight: normal;
                font-size: 12px;
            }

        .formstyle input[type=submit] {
            background: #EB3B88;
            border: 1px solid #C94A81;
            padding: 5px 15px 5px 15px;
            color: #FFCBE2;
            box-shadow: inset -1px -1px 3px #FF62A7;
            -moz-box-shadow: inset -1px -1px 3px #FF62A7;
            -webkit-box-shadow: inset -1px -1px 3px #FF62A7;
            border-radius: 3px;
            border-radius: 3px;
            -webkit-border-radius: 3px;
            -moz-border-radius: 3px;
            font-weight: bold;
        }
    h1 {
        color: #EB3B88;
    }
</style>
<center>

<hr />
<div class="total">
    <h1>Signup</h1>
    <div class="formstyle">
        <form asp-action="Signup">
            <fieldset>
                <legend>SignUp</legend>
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="UserId" class="control-label"></label>
                    <input asp-for="UserId" class="form-control" />
                    <span asp-validation-for="UserId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="control-label"></label>
                    <input asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Fullname" class="control-label"></label>
                    <input asp-for="Fullname" class="form-control" />
                    <span asp-validation-for="Fullname" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Joined" class="control-label"></label>
                    <input asp-for="Joined" class="form-control" />
                    <span asp-validation-for="Joined" class="text-danger"></span>
                </div>
                <br />
                <div class="form-group form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="Active" /> @Html.DisplayNameFor(model => model.Active)
                    </label>
                </div>
                <div class="form-group">
                    <input type="submit" value="Sign Up" class="btn btn-primary" />
                </div>
            </fieldset>
        </form>
    </div>
    

    <div>
        <a asp-action="/Twitter/Login">Sign In</a>
    </div>
</center>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TwitterClone/Views/Twitter/UserDashboard.cshtml
@model TwitterClone.Model.PersonTweetViewModel

@{
    ViewData["Title"] = "UserDashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    body {
        background-color: #87CEFA;
    }

    h1 {
        position: relative;
        right: -30%;
    }

    .abc {
        position: relative;
        right: -60%;
    }

    .b {
        position: relative;
        right: -40%;
        font-size: 50%;
        color: black;
    }

    .c {
        position: relative;
        right: -25%;
        font-size: 50%;
        color: black;
    }

    .d {
        position: relative;
        right: -11%;
        font-size: 50%;
        color: black;
    }

    .text {
        width: 70%;
        height: 200px;
        position: relative;
        right: -30%;
    }

    .follow, .example, .a {
        display: inline-block;
    }

    .textarea {
        position: relative;
        right: -60%;
    }

    .tweet {
        position: relative;
        right: -30%;
    }

    .button {
        position: relative;
        right: -60%;
        background-color: white;
    }

    .tweets, .button {
        display: inline-block;
    }

    .tweet, .followers {
        display: inline-block;
    }

    .tweet {
        position: relative;
        right: -24%;
        font-weight: bold;
    }

    .followers {
        position: relative;
        left: 0%;
        font-weight: bold;
    }

    .following {
        position: relative;
        left: 0%;
        font-weight: bold;
    }

    .tweet {
        position: relative;
        left: 0%;
    }

    .tweets {
        position: relative;
        right: -30%;
        font-weight: bold;
    }

    table {
        position: relative;
        padding: 15px;
        right: -30%;
        border: 1px solid black;
        text-align: left;
        border-bottom: 1px solid #ddd;
        width: auto;
    }

    tr:hover {
        background-color: #f5f5f5;
    }

    .tweetlist {
        position: relative;
        left: -46%;
    }

    button {
        float: right;
        padding: 6px 10px;
        margin-top: 8px;
        margin-right: 16px;
        background: #ddd;
        font-size: 17px;
        border: none;
        cursor: pointer;
    }

        button:hover {
            background: #ccc;
        }
</style>

<div>
    <form asp-action="/Twitter/Profile">
        <input type="text" placeholder="Search.." name="search">
        <button type="submit" value="Search"></button>
    </form>
    <ul id="myUL">
         @{
                 foreach (var item in Model.Persons)
                  {
                   <li><a href="/Twitter/Details?userid=@item.UserId">@item.Fullname</a></li>
                }
          }

        </ul>
</div>
@*<div>

        <h6 class="follow">Follow</h6>
        <br />
        <input type="text" placeholder="Search.." name="search">
    </div>*@
<div>
    <form class="example" asp-action="UserDashboard">
        <h6 class="abc">What are you doing?</h6>
        <br />
        <textarea class="textarea" asp-for=Tweet.Message rows="4" cols="50"></textarea>
        <br />
        <input type="submit" value="Update" class="button">
    </form>
</div>
<div>
    <h6 class="tweet">@ViewBag.Tweets Tweets</h6>
    <br />
    <h6 class="followers">@ViewBag.Followers Followers</h6>
    <br />
    <h6 class="following">@ViewBag.Following Following</h6>
</div>
<div>
    <label class="tweets">Tweets</label>
    <table>
        <tr>
            <th>Tweet ID</th>
            <th>Message</th>
            <th>Time</th>

        </tr>
        @foreach (var item in Model.TweetsList)
        {
            <tr>
                <td>@item.TweetId</td>
                <td>@item.Message</td>
                <td>@item.Created.ToShortDateString()</td>

            </tr>
        }
    </table>

</div>


@*<style>
        body {
            background-color: #5c9acf;
        }

        h1 {
            position: relative;
            right: -30%;
        }

        .a {
            position: relative;
            right: -40%;
        }

        .b {
            position: relative;
            right: -40%;
            font-size: 50%;
            color: black;
        }

        .c {
            position: relative;
            right: -25%;
            font-size: 50%;
            color: black;
        }

        .d {
            position: relative;
            right: -11%;
            font-size: 50%;
            color: black;
        }

        .text {
            width: 70%;
            height: 200px;
            position: relative;
            right: -30%;
        }

        .follow, .example, .a {
            display: inline-block;
        }

        .textarea {
            position: relative;
            right: -40%;
        }

        .tweet {
            position: relative;
            right: -30%;
        }

        .button {
            position: relative;
            left: 95%;
            background-color: white;
        }

        .tweets, .button {
            display: inline-block;
        }

        .tweet, .followers {
            display: inline-block;
        }

        .tweet {
            position: relative;
            right: -24%;
            font-weight: bold;
        }

        .followers {
            position: relative;
            left: 0%;
            font-weight: bold;
        }

        .following {
            position: relative;
            left: 0%;
            font-weight: bold;
        }

        .tweet {
            position: relative;
            left: 0%;
        }

        table {
            position: relative;
            right: -30%;
        }

        .tweetlist {
            position: relative;
            left: -46%;
        }
    </style>
    <h1>
        My Twitter Clone
        <a href="/Twitter/Login" class="b">Signout</a>
        <a href="/Twitter/Profile" class="c">Profile</a>
        <a href="/Twitter/UserDashboard" class="d">Home</a>
    </h1>
    <br />
    <h6 class="follow">Follow</h6>
    <form class="example" action="action_page.php">
        <input type="text" placeholder="Search.." name="search">
    </form>

    <div class="table">
        <form class="example" asp-action="UserDashboard">
            <h6 class="a">What are you doing?</h6>
            <br />
            <textarea class="textarea" asp-for=Tweet.Message rows="4" cols="100"></textarea>
            <br />
            <input type="button" value="Update" class="button" />
            <br />
        </form>
    </div>
    <div>
        <h6 class="tweet">@ViewBag.Tweets Tweets</h6><br />
        <h6 class="followers">@ViewBag.Followers Followers</h6>
        <h6 class="following">@ViewBag.Following Following</h6>
        <h1 class="tweets">Tweets</h1>
        <table>
            <tr>
                <th>Tweet ID</th>
                <th>Message</th>
                <th>Time</th>

            </tr>
            @foreach (var item in Model.TweetsList)
            {
                <tr>
                    <td>@item.TweetId</td>
                    <td>@item.Message</td>
                    <td>@item.Created.Date</td>

                </tr>
            }
        </table>

    </div>*@